title = "KEEP LEARNING"
baseURL = "https://jerrykuan.github.io/jerryfan.github.io/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"
publishDir = "public"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10     # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "KEEP LEARNING"
  facebook = "https://www.facebook.com/profile.php?id=100011445841079"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://www.instagram.com/jerry_fanjk/"
  youtube = ""
  github = "https://github.com/JerryKuan"
  gitlab = ""
  linkedin = "https://www.linkedin.com/feed/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2